-- Drop tables if they already exist --

DROP TABLE IF EXISTS `CUSTOMER_PHONE`; 
DROP TABLE IF EXISTS `PHONE`;
DROP TABLE IF EXISTS `CUSTOMER`;
DROP TABLE IF EXISTS `CREDIT_CARD`;
DROP TABLE IF EXISTS `CABIN`; 
DROP TABLE IF EXISTS `ADDRESS`; 
DROP TABLE IF EXISTS `CRUISE`; 
DROP TABLE IF EXISTS `SHIP`; 
DROP TABLE IF EXISTS `RESERVATION`; 



CREATE TABLE CABIN (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    SHIP_ID INT,
    BED_COUNT INT,
    NAME CHAR(30),
    DECK_LEVEL INT
);

CREATE TABLE ADDRESS (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    STREET CHAR(40),
    CITY CHAR(20),
    STATE CHAR(2),
    ZIP CHAR(10)
);


CREATE TABLE CREDIT_CARD (
   ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
   EXPIRATION_DATE DATE,
   NUMBER CHAR(40),
   NAME CHAR(40),
   ORGANIZATION CHAR(20)
);


CREATE TABLE CUSTOMER (
   ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
   FIRSTNAME VARCHAR(255),
   LASTNAME VARCHAR(255),
   ADDRESS_ID INT,
   CREDIT_CARD_ID INT,
   FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID), 
   FOREIGN KEY (CREDIT_CARD_ID) REFERENCES CREDIT_CARD (ID)
 );

CREATE TABLE PHONE (
     ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
     NUMBER CHAR(20),
     TYPE INT,
     CUSTOMER_ID BIGINT,
     FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
 );

-- ALTERNATIVE WAY TO REPRESENT ONE-TO-MANY RELATIONSHIPS WITH A JOIN TABLE --

-- CREATE TABLE CUSTOMER_PHONE (
--    CUSTOMER_ID INT NOT NULL,
--    PHONE_ID INT UNIQUE
-- );

CREATE TABLE SHIP (
   ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
   NAME CHAR(30),
   TONNAGE DECIMAL(8,2)
);

CREATE TABLE CRUISE (
   ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
   NAME CHAR(30),
   SHIP_ID INT
);

ALTER TABLE CRUISE ADD CONSTRAINT cruiseREFship
   FOREIGN KEY (SHIP_ID) REFERENCES SHIP(ID);

CREATE TABLE RESERVATION (
    ID INT PRIMARY KEY AUTO_INCREMENT  NOT NULL,
    AMOUNT_PAID DECIMAL(8,2),
    DATE_RESERVED DATE,
    CRUISE_ID INT
);
