CREATE TABLE CABIN (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    SHIP_ID INT,
    BED_COUNT INT,
    NAME CHAR(30),
    DECK_LEVEL INT
);

CREATE TABLE ADDRESS (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    STREET CHAR(40),
    CITY CHAR(20),
    STATE CHAR(2),
    ZIP CHAR(10)
);

CREATE TABLE CUSTOMER (
   ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
   FIRSTNAME VARCHAR(255),
   LASTNAME VARCHAR(255),
   ADDRESS_ID INT,
   FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID)
 )


